name: 💫

on: [watch]

permissions:
  contents: write

jobs:
  addstars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add watcher to readme
      run: |
        git config --global user.name web-flow
        git config --global user.email noreply@github.com
        
        echo -e "\nWe got a :star: from [@${{github.actor}}](https://github.com/${{github.actor}})" >> README.md
        git add README.md
        git commit -m "💫"
        git push
